### ISSUE TITLE
Link error(Using ASIO, undefined reference to tinyrpc::TinyCommBase<asio::ip::basic_endpointasio::ip::tcp >::PKG_MAGIC_HEAD')

### ISSUE THREAD

**Issue by xc42** [hjk41/Remmy#7]
using WSL Arch Linux，gcc version 10.2.0 (GCC)

Running `make` in test directory
got following link error, have no idea why this occur

> g++ test.cpp -o test --std=c++14 -I../tinyrpc --std=c++14 -O0 -g -fpermissive -pthread -DUSE_ASIO=1 -DASIO_STANDALONE=1 -I../tinyrpc/asio/asio/include -lpthread
/usr/sbin/ld: /usr/sbin/ld: DWARF error: could not find variable specification at offset 2bf75
/usr/sbin/ld: DWARF error: could not find variable specification at offset 306bc
/usr/sbin/ld: DWARF error: could not find variable specification at offset 3077d
/usr/sbin/ld: DWARF error: could not find variable specification at offset 2f01e
/usr/sbin/ld: DWARF error: could not find variable specification at offset 30607
/usr/sbin/ld: DWARF error: could not find variable specification at offset 30552
/usr/sbin/ld: DWARF error: could not find variable specification at offset 3049d
/usr/sbin/ld: DWARF error: could not find variable specification at offset 2be5b
/tmp/ccyaxXsU.o: in function `tinyrpc::TinyCommAsio::Send(std::shared_ptr<tinyrpc::Message<asio::ip::basic_endpoint<asio::ip::tcp> > > const&)':
/home/hexagon/Codes/CCXX/tinyrpc/test/../tinyrpc/comm_asio.h:188: undefined reference to `tinyrpc::TinyCommBase<asio::ip::basic_endpoint<asio::ip::tcp> >::PKG_MAGIC_HEAD'
/usr/sbin/ld: /tmp/ccyaxXsU.o: in function `tinyrpc::TinyCommAsio::AsyncSend(std::shared_ptr<tinyrpc::Message<asio::ip::basic_endpoint<asio::ip::tcp> > > const&, std::function<void (std::shared_ptr<tinyrpc::Message<asio::ip::basic_endpoint<asio::ip::tcp> > > const&, tinyrpc::CommErrors)> const&)':
/home/hexagon/Codes/CCXX/tinyrpc/test/../tinyrpc/comm_asio.h:219: undefined reference to `tinyrpc::TinyCommBase<asio::ip::basic_endpoint<asio::ip::tcp> >::PKG_MAGIC_HEAD'
collect2: error: ld returned 1 exit status
make: *** [Makefile:18: test] Error 1

**Comment by hjk41** [comment]
Seems like a gcc bug: https://sourceware.org/bugzilla/show_bug.cgi?id=26520
Try another version of GCC.

**Comment by xc42** [comment]
> 
> 
> Seems like a linker bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=965247

emm...maybe part of ...
I also tried compile on ubuntu 16.04 with `gcc --version` (g++ (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609)
running `make` still got "undefined reference to ..." link error, but without the DWARF error

> g++ test.cpp -o test --std=c++14 -I../tinyrpc --std=c++14 -O0 -g -fpermissive -pthread -DUSE_ASIO=1 -DASIO_STANDALONE=1 -I../tinyrpc/asio/asio/include -lpthread -static-libstdc++ -static-libgcc
/tmp/ccD0dW7O.o: In function `tinyrpc::TinyCommAsio::Send(std::shared_ptr<tinyrpc::Message<asio::ip::basic_endpoint<asio::ip::tcp> > > const&)':
/root/Codes/CCXX/tinyrpc/test/../tinyrpc/comm_asio.h:187: undefined reference to `tinyrpc::TinyCommBase<asio::ip::basic_endpoint<asio::ip::tcp> >::PKG_MAGIC_HEAD'
/tmp/ccD0dW7O.o: In function `tinyrpc::TinyCommAsio::AsyncSend(std::shared_ptr<tinyrpc::Message<asio::ip::basic_endpoint<asio::ip::tcp> > > const&, std::function<void (std::shared_ptr<tinyrpc::Message<asio::ip::basic_endpoint<asio::ip::tcp> > > const&, tinyrpc::CommErrors)> const&)':
/root/Codes/CCXX/tinyrpc/test/../tinyrpc/comm_asio.h:218: undefined reference to `tinyrpc::TinyCommBase<asio::ip::basic_endpoint<asio::ip::tcp> >::PKG_MAGIC_HEAD'
collect2: error: ld returned 1 exit status
Makefile:17: recipe for target 'test' failed
make: *** [test] Error 1

PS: the original code int test.cpp main function the line `std::atomic<size_t> size = 0;` with cause compile error

>     use of deleted function ‘std::atomic<long unsigned int>::atomic(const std::atomic<long unsigned int>&)’
change to `std::atomic<size_t> size = {0}` fix it

**Comment by hjk41** [comment]
try the latest commit.

**Comment by xc42** [comment]
> 
> 
> try the latest commit.

all works now, thanks
